language: node_js

node_js:
  - '12'


# Needed for Cypress
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - yarn
    - yarn cy:verify

cache: yarn

install:
  - yarn
  - yarn global add codecov

after_success:
  - codecov

