language: node_js

node_js:
  - '10'


# Needed for Cypress
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - yarn
    - yarn cy:verify

cache: yarn

before_script:
  - yarn build

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn ci

after_success:
  - codecov

