version: 2
jobs:
  build:
    working_directory: ~/project-name

    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run: npx plek now komfy.now.sh --app 'komfy' -- --public

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
